FROM python:3.9-slim

WORKDIR /app

COPY server.py /app/server.py
COPY crawler.cfg /app/crawler.cfg

RUN pip install --no-cache-dir requests configparser

EXPOSE 8015

CMD ["python3", "/app/server.py"]
